### ISSUE TITLE
license and copyright

### ISSUE THREAD

**Issue by hannesm** [leostera/blink#2]
Dear Leonardo,

I appreciate your contributions and work o OCaml related projects.

I noticed that e.g. in blink/ssl.ml there's lots of code that I found originating from ocaml-tls (lwt/x509_lwt.ml) and ca-certs (lib/ca_certs.ml). What I'd appreciate, if you copy-paste code from other libraries (in huge chunks) to put attribution to the original authors into the code ("provided that the above copyright notice and this permission notice appear in all copies" is a common part of permissive licenses).

What is your opinion on this topic? I understand there's work involved if you copy and paste code -- namely tracking the authorship and licenses. But, to be honest, this is fair and should be self-evident. I already feel sad that I've to open such an issue.

**Comment by leostera** [comment]
Oversight from my side 🙏🏼 will fix it immediately!

**Comment by leostera** [comment]
Really sorry about this, I've added a notice referencing the modules we ported over to Riot here https://github.com/leostera/blink/blob/main/blink/ssl.ml#L1-L13 – please let me know if this is ok with you or if you want something else to be added 🙏🏼 

I'm a huge fan of your work, and I appreciate you opening this issue and pointing out where I'm falling short. Thank you!

**Comment by leostera** [comment]
I've also updated the [pending 0.0.1 release PR](https://github.com/ocaml/opam-repository/pull/24990) for opam to include this newer version with better attribution.

**Comment by hannesm** [comment]
Thanks for your quick reply and putting attribution into the source.
